import { useState } from "react";
import { hasSupabaseConfig, supabase } from "../supabaseClient";

function Brand() { return <div className="brand brand-light"><span className="brand-mark">R</span><span>RECORDATE</span></div>; }

function Login({ onLogin, onDemo, onBack }) {
  const [isSignUp, setIsSignUp] = useState(false); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [fullName, setFullName] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  const handleSubmit = async (event) => { event.preventDefault(); setMessage(""); if (isSignUp && !fullName.trim()) { setMessage("Escribe tu nombre para crear la cuenta."); return; } if (password.length < 6) { setMessage("La contraseña debe tener mínimo 6 caracteres."); return; } if (!hasSupabaseConfig) { setMessage("La autenticación real requiere configurar Supabase. Puedes explorar el acceso DEMO."); return; } setLoading(true); try { const result = isSignUp ? await supabase.auth.signUp({ email, password, options: { data: { full_name: fullName } } }) : await supabase.auth.signInWithPassword({ email, password }); if (result.error) setMessage(result.error.message); else if (result.data.session) onLogin(result.data.session); else setMessage("Revisa tu correo para confirmar la cuenta."); } catch { setMessage("No fue posible conectar con el servicio. Inténtalo de nuevo."); } finally { setLoading(false); } };
  return <main className="auth-page"><div className="auth-aside"><button className="back-link" onClick={onBack}>← Volver al inicio</button><Brand /><div className="auth-quote"><span className="eyebrow">Tu espacio académico</span><h1>Lo importante, <em>en el momento correcto.</em></h1><p>Una agenda clara para que puedas concentrarte en aprender.</p></div><span className="auth-footer">RECORDATE · PPI IE La Candelaria</span></div><section className="auth-panel"><div className="mobile-auth-brand"><Brand /></div><span className="eyebrow accent-label">{isSignUp ? "Comienza hoy" : "Bienvenido de nuevo"}</span><h2>{isSignUp ? "Crea tu cuenta." : "Entra a tu agenda."}</h2><p className="auth-subtitle">{isSignUp ? "Organiza tus actividades académicas desde el primer día." : "Tus tareas y recordatorios te están esperando."}</p><form onSubmit={handleSubmit} noValidate>{isSignUp && <label>Nombre<input value={fullName} onChange={(event) => setFullName(event.target.value)} required /></label>}<label>Correo electrónico<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} required /></label><label>Contraseña<input type="password" minLength="6" value={password} onChange={(event) => setPassword(event.target.value)} required /></label>{message && <p className="auth-message" role="alert">{message}</p>}<button className="primary-button auth-submit" type="submit" disabled={loading}>{loading ? "Conectando..." : isSignUp ? "Crear mi cuenta" : "Iniciar sesión"}<span>→</span></button></form><button className="demo-button" type="button" onClick={onDemo}>Explorar con acceso DEMO <span>↗</span></button><button className="switch-button" type="button" onClick={() => { setIsSignUp((current) => !current); setMessage(""); }}>{isSignUp ? "¿Ya tienes cuenta? Inicia sesión" : "¿No tienes cuenta? Regístrate"}</button><p className="auth-note">No guardamos contraseñas en este navegador.</p></section></main>;
}

export default Login;